# Generated by Django 3.0.2 on 2020-08-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('reward', models.IntegerField()),
                ('about', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('ip', models.GenericIPAddressField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('location', models.TextField()),
                ('end_date', models.DateField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('Class', models.CharField(blank=True, max_length=300, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('intrests', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('intrests', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=800)),
            ],
        ),
    ]
