# Generated by Django 3.0.2 on 2020-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table='challenge',
        ),
    ]
