# Generated by Django 3.0.2 on 2020-08-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200826_1850'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table='Challenge',
        ),
    ]
