# Generated by Django 3.0.2 on 2020-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200826_1903'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table=None,
        ),
    ]
