# Generated by Django 3.0.2 on 2020-08-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200826_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
