# Generated by Django 3.0.2 on 2020-08-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200826_1927'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table='Challenge',
        ),
    ]
