# Generated by Django 3.0.2 on 2020-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
